Finished Page UI : Add ui for completed downloads
NevilleAntony98/Prototype pull request #28
Opened 2021-06-12 13:26 UTC by Nikhil713

2021-06-13 12:47 UTC, kss682 commented on app/src/main/java/com/nevilleantony/prototype/adapters/CompletedListAdapter.java
> +        downloadIntent = new Intent(context, DownloadService.class);
Do we need ```downloadIntent``` in completed page, this is for starting service in downloads page, right?

2021-06-13 16:35 UTC, NevilleAntony98 requested changes

2021-06-13 16:35 UTC, NevilleAntony98 commented on app/src/main/java/com/nevilleantony/prototype/adapters/CompletedListAdapter.java
> +        holder.downloadsName.setText(fileDownload.getName());
Here you also need to set an onClick listener on the share button, which creates an intent for ShareActivity.class. You should also add the absolute path of the file as an extra in the intent and call startActivity with it.

2021-06-13 16:35 UTC, NevilleAntony98 commented on app/src/main/res/layout/fragment_completed_list_row.xml
> +                android:text="@string/completed_filename_text"
This line can be removed

2021-06-13 16:35 UTC, NevilleAntony98 commented on app/src/main/res/values/strings.xml
> +    <string name="completed_filename_text">TextView</string>
This line can be removed

2021-06-15 05:13 UTC, NevilleAntony98 approved these changes

2021-06-15 05:16 UTC, merged